[package]
name = "fuzzy_bucket"
version = "0.1.0"
authors = ["jumzzz <jummel19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
